name: Docker Hub release

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract version
      id: extract_version
      uses: Saionaro/extract-package-version@v1.0.6
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: tombailey256
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: tombailey256/dead-link-detection:${{ steps.extract_version.outputs.version }}
